# Camera Configuration
device_id: 0  # Try device 0 first (USB camera)
resolution:
  width: 2592   # Native resolution for IMX335
  height: 1944
exposure_time: 100000  # microseconds (0.1 seconds)
gain: 5.0
auto_exposure: false
auto_gain: false

# Recording Configuration
output_directory: "recordings"
filename_format: "recording_%Y%m%d_%H%M%S.avi" 